In [18]:
import pandas as pd

In [19]:
books = pd.read_csv(
    "../data/raw/Books.csv",
    sep=";",
    encoding="latin-1",
    on_bad_lines="skip"
)

In [20]:
ratings = pd.read_csv(
    "../data/raw/Ratings.csv",
    sep=";",
    encoding="latin-1",
    on_bad_lines="skip"
)

In [21]:
books.head()

,ISBN,Title,Author,Year,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton & Company

In [22]:
books.shape
books.info()

<class 'pandas.DataFrame'>
RangeIndex: 271379 entries, 0 to 271378
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   ISBN       271379 non-null  str
 1   Title      271379 non-null  str
 2   Author     271377 non-null  str
 3   Year       271379 non-null  int64
 4   Publisher  271377 non-null  str
dtypes: int64(1), str(4)
memory usage: 10.4 MB

In [23]:
books[books.isnull().any(axis=1)]

,ISBN,Title,Author,Year,Publisher
118038,0751352497,A+ Quiz Masters:01 Earth,NaN,1999,Dorling Kindersley
128896,193169656X,Tyrant Moon,Elaine Corvidae,2002,NaN
129043,1931696993,Finders Keepers,Linnea Sinclair,2001,NaN
187700,9627982032,The Credit Suisse Guide to Managing Your Perso...,NaN,1995,Edinburgh Financial Publishing

In [24]:
books_clean = books.dropna()
books_clean.info()

<class 'pandas.DataFrame'>
Index: 271375 entries, 0 to 271378
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   ISBN       271375 non-null  str
 1   Title      271375 non-null  str
 2   Author     271375 non-null  str
 3   Year       271375 non-null  int64
 4   Publisher  271375 non-null  str
dtypes: int64(1), str(4)
memory usage: 12.4 MB

In [25]:
books_clean["Year"].describe()

count    271375.000000
mean       1959.755468
std         258.013219
min           0.000000
25%        1989.000000
50%        1995.000000
75%        2000.000000
max        2050.000000
Name: Year, dtype: float64

In [26]:
books_clean["Year"].sort_values().head(20)

216109    0
131951    0
51679     0
131952    0
159349    0
158575    0
132020    0
234307    0
132032    0
267950    0
250150    0
140430    0
250149    0
165715    0
165691    0
149980    0
131954    0
185150    0
131955    0
190692    0
Name: Year, dtype: int64

In [27]:
books_clean["Year"].sort_values(ascending=False).head(20)

97830     2050
80267     2050
116058    2038
255426    2037
240184    2030
193004    2030
37488     2030
228187    2030
55679     2030
260992    2030
78171     2030
118299    2026
246858    2024
183779    2021
92160     2020
238832    2020
30011     2020
199207    2012
12783     2011
235440    2011
Name: Year, dtype: int64

In [28]:
books_clean[
    (books_clean["Year"] < 1900) |
    (books_clean["Year"] > 2025)
].shape

(4635, 5)

In [29]:
books_clean[
    (books_clean["Year"] <= 1900) |
    (books_clean["Year"] > 2025)
]["Year"].value_counts().head(20)

Year
0       4619
2030       7
1900       3
2050       2
2038       1
2026       1
1806       1
1378       1
1897       1
1376       1
2037       1
Name: count, dtype: int64

In [30]:
books_clean[
    books_clean["Year"].isin([1376, 1378, 1806, 1897, 2030, 2037, 2038, 2050])
]

,ISBN,Title,Author,Year,Publisher
37488,0671746103,MY TEACHER FRIED MY BRAINS (RACK SIZE) (MY TEA...,Coville,2030,Aladdin
55679,0671791990,MY TEACHER FLUNKED THE PLANET (RACK SIZE) (MY ...,Bruce Coville,2030,Aladdin
78171,0870449842,Crossing America,National Geographic Society,2030,National Geographic
80267,0140301690,Alice's Adventures in Wonderland and Through t...,Lewis Carroll,2050,Puffin Books
97830,0140201092,Outline of European Architecture (Pelican S.),Nikolaus Pevsner,2050,Penguin USA
116058,0394701658,Three Plays of Eugene Oneill,Eugene O'Neill,2038,Vintage Books USA
171826,0781228956,"Complete Works 10 Volumes [2,6,7,8,9] (Notable...",Benjamin Franklin,1806,Reprint Services Corp
193004,0870446924,"Field Guide to the Birds of North America, 3rd...",National Geographic Society,2030,National Geographic
227544,9643112136,Dalan-i bihisht (Dastan-i Irani),Nazi Safavi,1378,Intisharat-i Quqnus
228187,0671266500,FOREST PEOPLE (Touchstone Books (Hardcover)),Colin M. Turnbull,2030,Simon & Schuster
240184,0684718022,In Our Time: Stories (Scribner Classic),Ernest Hemingway,2030,Collier Books
245622,0781268001,"Hugh Wynne, Free Quaker (2 Volumes (BCL1-PS Am...",Silas Weir Mitchell,1897,Reprint Services Corp
253767,964442011X,Tasht-i khun,IsmaÃÂ°il Fasih,1376,Nashr-i Alburz
255426,068471809X,To Have and Have Not,Ernest Hemingway,2037,Simon & Schuster
260992,0671740989,FOOTBALL SUPER TEAMS : FOOTBALL SUPER TEAMS,Bill Gutman,2030,Simon & Schuster Children's Publishing

In [31]:
books_clean.loc[
    books_clean["Year"] == 0,
    "Year"
] = pd.NA

In [32]:
books_clean.loc[
    books_clean["Year"] > 2025,
    "Year"
] = pd.NA

In [33]:
ratings.shape
ratings.head()

   User-ID        ISBN  Rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [34]:
ratings["Rating"].value_counts().sort_index()

Rating
0     716109
1       1770
2       2759
3       5996
4       8904
5      50974
6      36924
7      76457
8     103736
9      67541
10     78610
Name: count, dtype: int64

In [35]:
ratings_explicit = ratings[ratings["Rating"] > 0]

ratings_explicit["User-ID"].nunique()

77805

In [36]:
ratings_explicit["ISBN"].nunique()

185973

In [37]:
user_rating_counts = ratings_explicit.groupby("User-ID").size()

user_rating_counts.describe()

count    77805.000000
mean         5.573819
std         44.001879
min          1.000000
25%          1.000000
50%          1.000000
75%          3.000000
max       8524.000000
dtype: float64

In [38]:
(user_rating_counts == 1).sum()

np.int64(45382)

In [39]:
book_rating_counts = ratings_explicit.groupby("ISBN").size()

book_rating_counts.describe()

count    185973.000000
mean          2.331903
std           6.834667
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max         707.000000
dtype: float64

In [40]:
(book_rating_counts == 1).sum()

np.int64(129621)

In [41]:
book_stats = (
    ratings_explicit
    .groupby("ISBN")
    .agg(
        avg_rating=("Rating", "mean"),
        num_ratings=("Rating", "count")
    )
)

book_stats.head()
book_stats.describe()

          avg_rating    num_ratings
count  185973.000000  185973.000000
mean        7.491347       2.331903
std         1.731428       6.834667
min         1.000000       1.000000
25%         6.500000       1.000000
50%         8.000000       1.000000
75%         9.000000       2.000000
max        10.000000     707.000000

In [42]:
book_stats.sort_values(
    "avg_rating",
    ascending=False
).head(20)

                avg_rating  num_ratings
ISBN
2877141500            10.0            1
X000000000            10.0            1
'9607092910'          10.0            1
SBN67001026X          10.0            1
\"8887517452\"        10.0            1
\"9170010242\"        10.0            1
2877141268            10.0            1
3805206763            10.0            1
380520700X            10.0            1
0785383743            10.0            1
0785806040            10.0            1
0785807233            10.0            1
0785808116            10.0            1
0785787135            10.0            1
0785787534            10.0            1
0785788727            10.0            1
0785800328            10.0            1
0785801863            10.0            1
0330024841            10.0            1
0785811966            10.0            1

In [43]:
popular_books = book_stats[
    book_stats["num_ratings"] >= 20
]

popular_books.sort_values(
    "avg_rating",
    ascending=False
).head(20)

            avg_rating  num_ratings
ISBN
0439425220    9.869565           23
0060256656    9.750000           20
0618002235    9.720000           25
8826703132    9.714286           21
0836218221    9.600000           20
0836220889    9.583333           24
0743454529    9.545455           22
0140143505    9.464286           28
0345339738    9.402597           77
0060256672    9.400000           25
0553274325    9.391304           23
0156012197    9.391304           23
0836217691    9.350000           20
0440174643    9.333333           21
039480001X    9.312500           32
0836221362    9.300000           20
0920668372    9.280000           25
1880418568    9.272727           22
0439139597    9.262774          137
0836204387    9.260870           23

In [44]:
C = ratings_explicit["Rating"].mean()
print(C)

7.601066246071331

In [45]:
m = 20

In [46]:
book_stats["weighted_rating"] = (
    (book_stats["num_ratings"] /
     (book_stats["num_ratings"] + m))
    * book_stats["avg_rating"]
    +
    (m /
     (book_stats["num_ratings"] + m))
    * C
)

In [47]:
book_stats.sort_values(
    "weighted_rating",
    ascending=False
)[["avg_rating",
   "num_ratings",
   "weighted_rating"]].head(20)

            avg_rating  num_ratings  weighted_rating
ISBN
0439139597    9.262774          137         9.051091
0345339738    9.402597           77         9.031148
043935806X    9.033981          206         8.907174
0439136369    9.082707          133         8.889028
059035342X    8.939297          313         8.858923
0439136350    9.035461          141         8.857275
0446310786    8.943925          214         8.829151
0345339711    9.120482           83         8.825450
0439425220    9.869565           23         8.814449
0590353403    8.983193          119         8.784326
0618002235    9.720000           25         8.778252
043936213X    9.207547           53         8.767415
0439139600    8.954545          110         8.746318
0439064864    8.920635          126         8.739872
0064400557    9.073529           68         8.738879
0140143505    9.464286           28         8.687944
0441172717    8.973333           75         8.684435
8826703132    9.714286           21         8.683447
0836220889    9.583333           24         8.682303
0345339703    8.839695          131         8.675638

In [48]:
user_counts = ratings_explicit.groupby("User-ID").size()
book_counts = ratings_explicit.groupby("ISBN").size()

filtered_ratings = ratings_explicit[
    ratings_explicit["User-ID"].isin(
        user_counts[user_counts >= 5].index
    )
]

filtered_ratings = filtered_ratings[
    filtered_ratings["ISBN"].isin(
        book_counts[book_counts >= 5].index
    )
]

filtered_ratings.shape

(152280, 3)

In [49]:
filtered_ratings["User-ID"].nunique()

13305

In [50]:
filtered_ratings["ISBN"].nunique()

14513

In [51]:
user_to_idx = {
    user_id: idx
    for idx, user_id in enumerate(
        filtered_ratings["User-ID"].unique()
    )
}

book_to_idx = {
    isbn: idx
    for idx, isbn in enumerate(
        filtered_ratings["ISBN"].unique()
    )
}

In [52]:
filtered_ratings["user_idx"] = (
    filtered_ratings["User-ID"]
    .map(user_to_idx)
)

filtered_ratings["book_idx"] = (
    filtered_ratings["ISBN"]
    .map(book_to_idx)
)

In [53]:
filtered_ratings.head()

     User-ID        ISBN  Rating  user_idx  book_idx
16    276747  0060517794       9         0         0
19    276747  0671537458       9         0         1
20    276747  0679776818       8         0         2
120   276813  8426449476       8         1         3
133   276822  0060096195      10         2         4

In [54]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    filtered_ratings,
    test_size=0.2,
    random_state=42
)

print("Train:", train_df.shape)
print("Test :", test_df.shape)

Train: (121824, 5)
Test : (30456, 5)

In [55]:
n_users = train_df["user_idx"].nunique()
n_books = train_df["book_idx"].nunique()

print("Users:", n_users)
print("Books:", n_books)

Users: 13008
Books: 14472

In [56]:
import numpy as np

K = 20  # latent factors

U = np.random.normal(
    scale=0.1,
    size=(n_users, K)
)

V = np.random.normal(
    scale=0.1,
    size=(n_books, K)
)

print(U.shape)
print(V.shape)

(13008, 20)
(14472, 20)

In [57]:
sample = train_df.iloc[0]

user_idx = sample["user_idx"]
book_idx = sample["book_idx"]
actual_rating = sample["Rating"]

print("User:", user_idx)
print("Book:", book_idx)
print("Actual Rating:", actual_rating)

User: 11120
Book: 3250
Actual Rating: 10

In [58]:
pred_rating = np.dot(
    U[user_idx],
    V[book_idx]
)

print("Predicted:", pred_rating)

Predicted: 0.021845409416175358

In [59]:
error = actual_rating - pred_rating

print(error)

9.978154590583825

In [60]:
loss = error ** 2

print(loss)

99.56356903358906

In [61]:
print(U[user_idx][:5])
print(V[book_idx][:5])

[-0.05575292  0.07012863  0.1373025   0.06545144 -0.22604354]
[-0.12641708  0.18344873 -0.01187376 -0.05118075 -0.10694915]

In [62]:
lr = 0.01

In [63]:
u_old = U[user_idx].copy()
v_old = V[book_idx].copy()

In [64]:
U[user_idx] += lr * error * v_old
V[book_idx] += lr * error * u_old

In [65]:
new_pred = np.dot(
    U[user_idx],
    V[book_idx]
)

print("Old prediction:", pred_rating)
print("New prediction:", new_pred)

Old prediction: 0.021845409416175358
New prediction: 0.06844327696317097

In [66]:
train_df.to_csv(
    "../data/processed/train.csv",
    index=False
)

test_df.to_csv(
    "../data/processed/test.csv",
    index=False
)

In [67]:
idx_to_book = {
    idx: isbn
    for isbn, idx in book_to_idx.items()
}

In [68]:
book_to_idx.items()

dict_items([('0060517794', 0), ('0671537458', 1), ('0679776818', 2), ('8426449476', 3), ('0060096195', 4), ('0375821813', 5), ('0552546933', 6), ('0786817070', 7), ('3257200552', 8), ('3404148576', 9), ('3404921178', 10), ('3423071516', 11), ('3426029553', 12), ('3442413508', 13), ('3442435773', 14), ('3442437717', 15), ('3442441080', 16), ('3442446414', 17), ('3442448530', 18), ('3442449820', 19), ('347354034X', 20), ('3551551677', 21), ('3551551685', 22), ('3551551693', 23), ('3551551936', 24), ('360893541X', 25), ('3608935428', 26), ('0836218833', 27), ('0836220889', 28), ('088365721X', 29), ('0141011904', 30), ('3423201509', 31), ('3404139178', 32), ('345309221X', 33), ('042518109X', 34), ('8817106100', 35), ('8838910987', 36), ('0440414121', 37), ('002542730X', 38), ('0099414732', 39), ('0140154078', 40), ('0385504209', 41), ('063403541X', 42), ('8420432113', 43), ('950491036X', 44), ('059030271X', 45), ('0671021354', 46), ('2020564777', 47), ('2070404587', 48), ('2264031158', 49), ('2266102621', 50), ('2266104535', 51), ('2070419657', 52), ('2253063339', 53), ('2253137243', 54), ('2253144452', 55), ('226612269X', 56), ('8423310353', 57), ('3423118709', 58), ('0345348672', 59), ('0345354621', 60), ('0345435036', 61), ('0425104273', 62), ('0440218667', 63), ('0440220602', 64), ('0684867621', 65), ('0812550307', 66), ('0843949163', 67), ('0886773741', 68), ('0886774802', 69), ('0886774829', 70), ('0886775426', 71), ('0886775957', 72), ('0061083259', 73), ('0061094404', 74), ('0671793489', 75), ('3423202327', 76), ('3492045170', 77), ('3548359698', 78), ('3596214629', 79), ('0312283709', 80), ('0446605484', 81), ('0446611212', 82), ('0451207955', 83), ('0609804138', 84), ('074343627X', 85), ('0971880107', 86), ('0099845008', 87), ('0330262130', 88), ('0385720920', 89), ('0553262505', 90), ('8472230082', 91), ('081297106X', 92), ('0843951826', 93), ('0312979517', 94), ('0316154059', 95), ('0345450175', 96), ('0345452550', 97), ('0399146504', 98), ('0399146687', 99), ('0399147101', 100), ('0399148337', 101), ('0399148639', 102), ('0399148728', 103), ('0399150811', 104), ('0399151451', 105), ('0425183181', 106), ('0671024094', 107), ('0679450408', 108), ('074320607X', 109), ('0743486226', 110), ('0449213730', 111), ('0451173139', 112), ('0486282406', 113), ('0553580930', 114), ('080410946X', 115), ('0340734043', 116), ('0060391626', 117), ('0330332775', 118), ('055326611X', 119), ('0553347756', 120), ('0553379615', 121), ('0670869902', 122), ('0671021001', 123), ('0671647458', 124), ('1573221856', 125), ('030700645X', 126), ('0307127923', 127), ('0307302016', 128), ('0307302636', 129), ('0307987655', 130), ('039480001X', 131), ('0394800028', 132), ('0394800184', 133), ('039480029X', 134), ('039480967X', 135), ('059044297X', 136), ('0717283194', 137), ('0717283208', 138), ('0717283364', 139), ('0717283372', 140), ('0717284832', 141), ('0375708049', 142), ('9726101794', 143), ('9726106141', 144), ('0312195516', 145), ('0446608955', 146), ('0670892963', 147), ('0671646575', 148), ('0804114986', 149), ('0812507452', 150), ('0812515560', 151), ('0812515595', 152), ('0060542128', 153), ('0061009059', 154), ('0152050167', 155), ('0316776963', 156), ('033031582', 157), ('0345413903', 158), ('0375751513', 159), ('0380702843', 160), ('0380791978', 161), ('038081904X', 162), ('0385424736', 163), ('0385486804', 164), ('0385503857', 165), ('039304016X', 166), ('0399149562', 167), ('0399501487', 168), ('0425104338', 169), ('0425116840', 170), ('0425133516', 171), ('0425190749', 172), ('0440185327', 173), ('0440224764', 174), ('0440236061', 175), ('0440236738', 176), ('0440428130', 177), ('0441627404', 178), ('0446350982', 179), ('0446522384', 180), ('0446600415', 181), ('0446608890', 182), ('0451180739', 183), ('0451191153', 184), ('0451203593', 185), ('0452284449', 186), ('0552137030', 187), ('0553078925', 188), ('0553280368', 189), ('0553351672', 190), ('0553571656', 191), ('0553573926', 192), ('0553574566', 193), ('0553581929', 194), ('0671014420', 195), ('0671528904', 196), ('0671740504', 197), ('0671749897', 198), ('0671876821', 199), ('0679417648', 200), ('0679731148', 201), ('0679736042', 202), ('0736903054', 203), ('0740723367', 204), ('0743406176', 205), ('0743412028', 206), ('0743422082', 207), ('0743444477', 208), ('0743457943', 209), ('0767903382', 210), ('0786866845', 211), ('0810909650', 212), ('0811802981', 213), ('0811811409', 214), ('0812531353', 215), ('0836210263', 216), ('0836217691', 217), ('0836218515', 218), ('0836218817', 219), ('0836221192', 220), ('0836221311', 221), ('0836236688', 222), ('0843947888', 223), ('0887621112', 224), ('0890876517', 225), ('0898157803', 226), ('0932592007', 227), ('1400060265', 228), ('1565075722', 229), ('8251800811', 230), ('0316666343', 231), ('0345444892', 232), ('0399149821', 233), ('0671027360', 234), ('0380718340', 235), ('0440226414', 236), ('0553292722', 237), ('0553571885', 238), ('0312113420', 239), ('0312979533', 240), ('0345330129', 241), ('0440213320', 242), ('0449907635', 243), ('0552142379', 244), ('0752853694', 245), ('1558745718', 246), ('9068340344', 247), ('1400030382', 248), ('2221090810', 249), ('0312289723', 250), ('0316603570', 251), ('0316693200', 252), ('0345452577', 253), ('0345452593', 254), ('0385336322', 255), ('0385336357', 256), ('0385508042', 257), ('0385510438', 258), ('039915180X', 259), ('0399151877', 260), ('0440241537', 261), ('0446530891', 262), ('0446613843', 263), ('0515133302', 264), ('055308576X', 265), ('0553801589', 266), ('0553803409', 267), ('0671886665', 268), ('0684835983', 269), ('0743206045', 270), ('1558744150', 271), ('0316777722', 272), ('0374516812', 273), ('0375707166', 274), ('0679439382', 275), ('0679723161', 276), ('0140043519', 277), ('0140274286', 278), ('0312986769', 279), ('0028604199', 280), ('0140340203', 281), ('0786890436', 282), ('1400031346', 283), ('1400031354', 284), ('1588720756', 285), ('0374184232', 286), ('0380005166', 287), ('0380018179', 288), ('0385472943', 289), ('0399132414', 290), ('0440241073', 291), ('0671000306', 292), ('0671000314', 293), ('0671026682', 294), ('0671795740', 295), ('0345335058', 296), ('034539657X', 297), ('0380731851', 298), ('0425142485', 299), ('0425147363', 300), ('042516098X', 301), ('0440211727', 302), ('0440214041', 303), ('0440430712', 304), ('0446794031', 305), ('0451162145', 306), ('0553297260', 307), ('0553579754', 308), ('0812543262', 309), ('051510566X', 310), ('052594544X', 311), ('0743206061', 312), ('087542127X', 313), ('0747546290', 314), ('0061015725', 315), ('0312983395', 316), ('0425192032', 317), ('0446611638', 318), ('0451208765', 319), ('0451210840', 320), ('0451210875', 321), ('0553582763', 322), ('0449911160', 323), ('0553282980', 324), ('0671755056', 325), ('0812967224', 326), ('1573227889', 327), ('3499100045', 328), ('3937793003', 329), ('0061031550', 330), ('0312421273', 331), ('0345339681', 332), ('0345377443', 333), ('0440235162', 334), ('0609806564', 335), ('0679416498', 336), ('0887307876', 337), ('0929634063', 338), ('1551660717', 339), ('0395977894', 340), ('042518336X', 341), ('0553575538', 342), ('0679781587', 343), ('0767903579', 344), ('0671759361', 345), ('0064440044', 346), ('0446672211', 347), ('0446675059', 348), ('0452282152', 349), ('0679427430', 350), ('0345384377', 351), ('0440225701', 352), ('0446609943', 353), ('0553580191', 354), ('0553582917', 355), ('0385492081', 356), ('0374266441', 357), ('0375410287', 358), ('0385301499', 359), ('0449908186', 360), ('0679751602', 361), ('0679764925', 362), ('0679770151', 363), ('0767915062', 364), ('0804105820', 365), ('0451198948', 366), ('0515129968', 367), ('0553561537', 368), ('0060934417', 369), ('0316168815', 370), ('0316785261', 371), ('0345468694', 372), ('0452283205', 373), ('0452283868', 374), ('0684848406', 375), ('0743225325', 376), ('0743237188', 377), ('0312974256', 378), ('0312983301', 379), ('0380785218', 380), ('0446610550', 381), ('0451203771', 382), ('0515121843', 383), ('051512317X', 384), ('0515124214', 385), ('0515134384', 386), ('0515136263', 387), ('0515136379', 388), ('0515136530', 389), ('0515137111', 390), ('0375507876', 391), ('0156027321', 392), ('0446529788', 393), ('0553802542', 394), ('0688179088', 395), ('0743204697', 396), ('0767905385', 397), ('1551668904', 398), ('0316789089', 399), ('0374190666', 400), ('0385484518', 401), ('0399141464', 402), ('0399145087', 403), ('0446526126', 404), ('0486285537', 405), ('0679457526', 406), ('0684874350', 407), ('0688151981', 408), ('0743204735', 409), ('0761107363', 410), ('0786881852', 411), ('0895261901', 412), ('0743420373', 413), ('1853260282', 414), ('0345386108', 415), ('0446611778', 416), ('0515087491', 417), ('0515101486', 418), ('0515104175', 419), ('0316601950', 420), ('034543479X', 421), ('0374480095', 422), ('0446670251', 423), ('0804115761', 424), ('0821766570', 425), ('0060572965', 426), ('0061031410', 427), ('0061094129', 428), ('0312983433', 429), ('0345440064', 430), ('0380820889', 431), ('038533558X', 432), ('0399142649', 433), ('0440221048', 434), ('0446527041', 435), ('0446531588', 436), ('0446610607', 437), ('0446612510', 438), ('0449006522', 439), ('0449219364', 440), ('0449221512', 441), ('0449227545', 442), ('0451179153', 443), ('0451179897', 444), ('0451202473', 445), ('0451204301', 446), ('0451206525', 447), ('0515125490', 448), ('0515129038', 449), ('0515130389', 450), ('0515135968', 451), ('0553582364', 452), ('0671001795', 453), ('0684810387', 454), ('0786889667', 455), ('1551667517', 456), ('1551669625', 457), ('0752837168', 458), ('8845907341', 459), ('0725107251', 460), ('0060002492', 461), ('0061057894', 462), ('0140067647', 463), ('0345337662', 464), ('0373115431', 465), ('0380600129', 466), ('0380708655', 467), ('0425065553', 468), ('0440940001', 469), ('0446606812', 470), ('0449209830', 471), ('0515094978', 472), ('0553287532', 473), ('0670894508', 474), ('0671434225', 475), ('0671525808', 476), ('0804106304', 477), ('1556611536', 478), ('1558745017', 479), ('0156005891', 480), ('0316171565', 481), ('0373218192', 482), ('0373244487', 483), ('0373272898', 484), ('0373441762', 485), ('0373441851', 486), ('0373484003', 487), ('0440122090', 488), ('044022103X', 489), ('0440223571', 490), ('0446603589', 491), ('0515124621', 492), ('0671644459', 493), ('0671644475', 494), ('0743410181', 495), ('0778320065', 496), ('0778320286', 497), ('1551661586', 498), ('1551665344', 499), ('1551666960', 500), ('0020532105', 501), ('0060926317', 502), ('0060958014', 503), ('0140280553', 504), ('0156007819', 505), ('0156011042', 506), ('0345423135', 507), ('0375705619', 508), ('0385334923', 509), ('0385498802', 510), ('0440212723', 511), ('0451209907', 512), ('051512219X', 513), ('0671683993', 514), ('0688177859', 515), ('0802139256', 516), ('0060198346', 517), ('014025448X', 518), ('0312252617', 519), ('0385316925', 520), ('0385319568', 521), ('0385324057', 522), ('0385334710', 523), ('0385497466', 524), ('0399145060', 525), ('0399148019', 526), ('0446527017', 527), ('0446527130', 528), ('0553104136', 529), ('0671510126', 530), ('0671786458', 531), ('0743206029', 532), ('0060977493', 533), ('0140039589', 534), ('0224060198', 535), ('0349101779', 536), ('0440216745', 537), ('0446613436', 538), ('0553582755', 539), ('0671027123', 540), ('0743460529', 541), ('0840776381', 542), ('1556611188', 543), ('1556612257', 544), ('3596237874', 545), ('0449912302', 546), ('0451153553', 547), ('0451170385', 548), ('006091291X', 549), ('0140309578', 550), ('0385319959', 551), ('0399146431', 552), ('0679445315', 553), ('0691017840', 554), ('1573221775', 555), ('0140444173', 556), ('0345334531', 557), ('051513287X', 558), ('006091646X', 559), ('0140167153', 560), ('0312265859', 561), ('0312965338', 562), ('0374270325', 563), ('0439064872', 564), ('0439136369', 565), ('0439139600', 566), ('043935806X', 567), ('0446378445', 568), ('0671016768', 569), ('0786868414', 570), ('0884270610', 571), ('0375409440', 572), ('0380730847', 573), ('0385313667', 574), ('0399147195', 575), ('0425182908', 576), ('0440236053', 577), ('044661257X', 578), ('0553569058', 579), ('0688152449', 580), ('080410753X', 581), ('0146000579', 582), ('0312970234', 583), ('0345300742', 584), ('0345352459', 585), ('0345369335', 586), ('0380710870', 587), ('0394800168', 588), ('0394820371', 589), ('0399134883', 590), ('042513525X', 591), ('0425140032', 592), ('0425178102', 593), ('042518630X', 594), ('0440139791', 595), ('0440184622', 596), ('0440207622', 597), ('0440479002', 598), ('0451173392', 599), ('0515131229', 600), ('0553131834', 601), ('0553282700', 602), ('0553297988', 603), ('0590466178', 604), ('0671017128', 605), ('0671019961', 606), ('0671502522', 607), ('0671775715', 608), ('0786862572', 609), ('0812523466', 610), ('0886775981', 611), ('0060935464', 612), ('0385475721', 613), ('0312978340', 614), ('0312955006', 615), ('0425137937', 616), ('0440225590', 617), ('0515124060', 618), ('0553565095', 619), ('0743225406', 620), ('0786889152', 621), ('031284879X', 622), ('0425178765', 623), ('0425182878', 624), ('0440221595', 625), ('0446610038', 626), ('0449003787', 627), ('0449219461', 628), ('0553213180', 629), ('0553269216', 630), ('0874778883', 631), ('0553573616', 632), ('0671510053', 633), ('0679768203', 634), ('0684829746', 635), ('0140292683', 636), ('0140293450', 637), ('0330375253', 638), ('0345423097', 639), ('0385730586', 640), ('0752837613', 641), ('8873122933', 642), ('0449219399', 643), ('0312980140', 644), ('0312983298', 645), ('0312983867', 646), ('0312990456', 647), ('0312991460', 648), ('0345348176', 649), ('0345350499', 650), ('0425163717', 651), ('0425190927', 652), ('0425191583', 653), ('0441478123', 654), ('0449003183', 655), ('0451202503', 656), ('0515136557', 657), ('0671877445', 658), ('1400034779', 659), ('0060160713', 660), ('0060987561', 661), ('0140244824', 662), ('014028009X', 663), ('0140296298', 664), ('0142000205', 665), ('0316096199', 666), ('0316899984', 667), ('0375703063', 668), ('0385512147', 669), ('0425178900', 670), ('0439324599', 671), ('0440226430', 672), ('0440514428', 673), ('0446679593', 674), ('0449907481', 675), ('0451163524', 676), ('0452283221', 677), ('0515131083', 678), ('0553278355', 679), ('0553570870', 680), ('0671028014', 681), ('0671038184', 682), ('0671735594', 683), ('0679425268', 684), ('0684814994', 685), ('0688162827', 686), ('0688170528', 687), ('0743225082', 688), ('1882723007', 689), ('2877304892', 690), ('0061095052', 691), ('0061097314', 692), ('0440223202', 693), ('044023574X', 694), ('8408022938', 695), ('8466307125', 696), ('8497593197', 697), ('0425182215', 698), ('0451410017', 699), ('0515132039', 700), ('074341022X', 701), ('0743437802', 702), ('0060173289', 703), ('0385260075', 704), ('0440211263', 705), ('0553274503', 706), ('059035342X', 707), ('0679412956', 708), ('0767902890', 709), ('0439050006', 710), ('0440486599', 711), ('0894803700', 712), ('1558531025', 713), ('0553275739', 714), ('0553579606', 715), ('0002005018', 716), ('0312261594', 717), ('0316748641', 718), ('0446677450', 719), ('0451166892', 720), ('0446608653', 721), ('0446612545', 722), ('0446612618', 723), ('0451208080', 724), ('0553584383', 725), ('0007123817', 726), ('0486284735', 727), ('0553278223', 728), ('3257208626', 729), ('3257233051', 730), ('3453212150', 731), ('3492045642', 732), ('3498020862', 733), ('3596292646', 734), ('0060915544', 735), ('0375400117', 736), ('0385316895', 737), ('0385720106', 738), ('0425163407', 739), ('044023722X', 740), ('0446364800', 741), ('0446606383', 742), ('0553580388', 743), ('0786863986', 744), ('155874262X', 745), ('0060987103', 746), ('0151008116', 747), ('0375704965', 748), ('0525947647', 749), ('0804111359', 750), ('0060934700', 751), ('0060976977', 752), ('0064471047', 753), ('0066238501', 754), ('0142001740', 755), ('0373226063', 756), ('0373226144', 757), ('0373834446', 758), ('0373834489', 759), ('037582345X', 760), ('0380730448', 761), ('0380789035', 762), ('0380817845', 763), ('0380973634', 764), ('0380973650', 765), ('0380977281', 766), ('038097827X', 767), ('0439064864', 768), ('0439136350', 769), ('0439139597', 770), ('0451167317', 771), ('0451406176', 772), ('0451409256', 773), ('0451524934', 774), ('0451526341', 775), ('0553280325', 776), ('0590353403', 777), ('0618002219', 778), ('0618002227', 779), ('0679879242', 780), ('1563895730', 781), ('1931081727', 782), ('0312963009', 783), ('0380728729', 784), ('0812541642', 785), ('0380815923', 786), ('0385416342', 787), ('0517577402', 788), ('0743411269', 789), ('0451527747', 790), ('0060973897', 791), ('0060976845', 792), ('006101351X', 793), ('0449002632', 794), ('0449213773', 795), ('0452279690', 796), ('1573225126', 797), ('1878424319', 798), ('0312283784', 799), ('0553582682', 800), ('0425156842', 801), ('0452277337', 802), ('0805063897', 803), ('0060925000', 804), ('0060932759', 805), ('0061000280', 806), ('039914739X', 807), ('0486281965', 808), ('081296666X', 809), ('8807170698', 810), ('8845229041', 811), ('9770390107900', 812), ('0345441133', 813), ('0385335407', 814), ('0385490992', 815), ('0671888587', 816), ('0140179836', 817), ('0345348656', 818), ('0385496095', 819), ('0439099404', 820), ('0440241006', 821), ('0515131679', 822), ('068484267X', 823), ('1558743669', 824), ('006017143X', 825), ('0345313860', 826), ('0385306032', 827), ('042517736X', 828), ('0671868713', 829), ('0679401377', 830), ('0805056491', 831), ('0020427859', 832), ('0060558865', 833), ('0140230165', 834), ('0345369068', 835), ('0451184718', 836), ('0553564528', 837), ('0553571842', 838), ('0553576801', 839), ('055357695X', 840), ('0553583441', 841), ('0553583468', 842), ('0590021117', 843), ('0679893105', 844), ('0689710879', 845), ('0689710887', 846), ('0689710895', 847), ('0689711522', 848), ('0743260244', 849), ('0767912918', 850), ('0812533534', 851), ('0821772953', 852), ('0399144463', 853), ('0618231617', 854), ('0743444167', 855), ('0140185216', 856), ('0425174484', 857), ('0486272745', 858), ('0684717255', 859), ('0060083298', 860), ('0140293248', 861), ('0446610399', 862), ('2253007102', 863), ('2266084372', 864), ('3423105410', 865), ('3492207006', 866), ('0060191929', 867), ('0140107649', 868), ('0151001006', 869), ('0316603287', 870), ('0316693006', 871), ('0316769487', 872), ('0316779423', 873), ('0316779490', 874), ('0316969443', 875), ('0345339711', 876), ('0385420161', 877), ('0385470819', 878), ('0385505833', 879), ('0394574745', 880), ('0399148582', 881), ('0425184129', 882), ('0446523569', 883), ('0446525502', 884), ('0446525537', 885), ('0446527793', 886), ('0446531332', 887), ('0609605925', 888), ('0609606727', 889), ('0671042556', 890), ('0679442790', 891), ('067972768X', 892), ('0679732241', 893), ('0679746048', 894), ('0684874318', 895), ('0688180639', 896), ('0743230051', 897), ('1558747028', 898), ('1558747346', 899), ('1570717257', 900), ('0006510345', 901), ('0061092606', 902), ('0140366660', 903), ('0140622063', 904), ('0261102214', 905), ('0671894455', 906), ('0743222229', 907), ('0749391308', 908), ('0749396067', 909), ('0752804510', 910), ('1853260002', 911), ('2253001457', 912), ('2253043974', 913), ('2253049417', 914), ('2253140872', 915), ('0060934719', 916), ('0345370740', 917), ('0345403339', 918), ('0446300101', 919), ('0451456548', 920), ('0679801146', 921), ('0786886463', 922), ('0786889160', 923), ('156341029X', 924), ('1563411148', 925), ('1563899388', 926), ('0064405052', 927), ('015216250X', 928), ('0152162577', 929), ('0345391802', 930), ('0440219078', 931), ('0590897985', 932), ('038533334X', 933), ('0440222818', 934), ('0440224829', 935), ('044661162X', 936), ('0451185277', 937), ('0515134368', 938), ('0140065172', 939), ('0060529709', 940), ('0140274154', 941), ('0375704027', 942), ('0876850867', 943), ('0060256672', 944), ('0060928336', 945), ('0140070206', 946), ('0140077022', 947), ('014016930X', 948), ('0140253602', 949), ('0316777730', 950), ('0375501851', 951), ('038001503X', 952), ('039592720X', 953), ('0440215625', 954), ('0553268449', 955), ('0671003755', 956),

In [69]:
print(idx_to_book[0])
print(idx_to_book[1])
print(idx_to_book[2])

0060517794
0671537458
0679776818

In [70]:
books_clean.head()

,ISBN,Title,Author,Year,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999.0,W. W. Norton & Company

In [71]:
isbn_to_title = dict(
    zip(
        books_clean["ISBN"],
        books_clean["Title"]
    )
)

In [72]:

sample_isbn = idx_to_book[0]

print(sample_isbn)
print(isbn_to_title.get(sample_isbn))

0060517794
Little Altars Everywhere

In [73]:
books_clean.to_csv(
    "../data/processed/books_metadata.csv",
    index=False
)